### ISSUE TITLE
Migrate to .NET 8.0 

### ISSUE THREAD

**Issue by totocaca123** [StateSmith/StateSmith#250]
Currently it uses .net6 and .net 7 for CLI - source seems compatble with .net 8

**Comment by adamfk** [comment]
Hi @totocaca123, thanks for the report.

I think I have this fixed in CLI release 0.7.1.

I tested on linux (easier to uninstall/reinstall versions) and the latest StateSmith.Cli version 0.7.1 works well if I only have net6 or only net8. I didn't test net7.

Mind giving it a try? You should only need to run `dotnet tool update StateSmith.Cli --global` to get the latest 0.7.1.
