### ISSUE TITLE
simulator - new titles

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#287]
Below are some naming suggestions:
![image](https://github.com/StateSmith/StateSmith/assets/274012/4f6d60b8-84b1-4216-b1b2-b722b9d40380)

**Comment by emmby** [comment]
Updated titles. I ended up getting rid of the table headers because it's pretty self-explanatory and frees up space. Also it was hard to decide what to call the rightmost column that fit within the space (I didn't love Action because that could be interpreted as a UML action, which not every record was)

**Comment by adamfk** [comment]
Good call!

**Comment by adamfk** [comment]
@emmby can you close when satisfied?
