### ISSUE TITLE
Example integrating with Zephyr RTOS

### ISSUE THREAD

**Issue by beriberikix** [StateSmith/StateSmith#57]
Hello! Love the idea behind StateSmith. I was wondering if you had any examples showing how to integrate StateSmith into an RTOS like [Zephyr](https://www.zephyrproject.org/). Either by integrating with its [State Machines Framework](https://docs.zephyrproject.org/latest/services/smf/index.html) or show an alternative.

Cheers.

**Comment by adamfk** [comment]
Hi :)

I currently use StateSmith with FreeRTOS. It should work with Zephyr as well because it has no dependencies on any OS or anything (it can run baremetal). Are you running into issues?

I do plan to properly support multiple different code generation strategies in the future. This would make it easy for you to write a bit of code so that StateSmith would output code to work with Zephyr's state machine framework.

I don't currently have a stable API for that yet, but if you want to explore it anyway, take a look at https://github.com/StateSmith/StateSmith/blob/main/src/StateSmith/compiler/SpecificVertexValidator.cs

You would likely need to create your own vertex visitor to visit the different vertices in the state machine graph.

**Comment by amigomcu** [comment]
hi ,
zephyr os which have include fsm function,

https://docs.zephyrproject.org/3.1.0/services/smf/index.html

> Hello! Love the idea behind StateSmith. I was wondering if you had any examples showing how to integrate StateSmith into an RTOS like [Zephyr](https://www.zephyrproject.org/). Either by integrating with its [State Machines Framework](https://docs.zephyrproject.org/latest/services/smf/index.html) or show an alternative.
> 
> Cheers.

**Comment by adamfk** [comment]
Hi @beriberikix, are you still interested in having StateSmith output Zephyr SMF code? If so, I can create a template project to help get you started. We now have initial support for custom code generation.

**Comment by adamfk** [comment]
Doesn't look like there is any interest in this. Closing for now. We can reopen if someone would like to work on it.

**Comment by 7RST1** [comment]
Hello! I am part of a project team where StateSmith would be very useful, especially if it had Zephyr SMF support.

As I understand it, these types of custom user code generators would be complete separate repos/projects, with the user running it from there using the cli?

Needless to say, I am very new to this. A template project would be very useful!

**Comment by adamfk** [comment]
Hello @7RST1 :)

You don't need separate repos/projects for each fsm if you use the
StateSmith cli tool.

I need to learn more about Zephyr SMF so take my thoughts below as
uninformed.

Could you help me understand why you would like to use Zephyr SMF when
StateSmith generates c code that can already be used with Zephyr?

From my limited understanding, I think the main advantage of Zephyr SMF is
that it will use less program space, but I'm not sure how much.

Cons of SMF I think would be a bit slower, a bit more RAM, a bit harder to
debug, less UML2 compliant, and fewer features.

I'll reopen. Zephyr is super popular. We should add support, but it will
probably take some time without a champion.

**Comment by 7RST1** [comment]
You are correct to question this, as I don't have a good answer. Initially, it was for our familiarity with the framework and wanting to stay within Zephyr's conventions as much as possible. After testing and learning, the normal C++ seems like it will work just fine for our purpose.. So I won't push for it further.

Thank you for your work on this very cool and useful project!
